#+ endpoint: https://graphdb.dumontierlab.com/repositories/shapes-registry
#+ endpoint_in_url: False
#+ summary:  Get HCLS metadata for a SPARQL endpoint
#+ description: Get HCLS metadata for a SPARQL endpoint
#+ tags:
#+   - Statistics overview
#+ method: GET
# pagination: 100
#+ defaults:
#+   - sparqlendpoint_iri: https://bio2rdf.org/sparql

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX bl: <http://w3id.org/biolink/vocab/>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX idot: <http://identifiers.org/idot/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX void-ext: <http://ldf.fi/void-ext#>
SELECT DISTINCT ?graph ?subjectCount ?subject ?predicate ?objectCount ?object
WHERE {
  GRAPH <?sparql_endpoint> {
    # ?graph a void:Dataset .
    ?graph void:propertyPartition [
      void:property ?predicate ;
      void:classPartition [
        void:class ?subject ;
        void:distinctSubjects ?subjectCount ;
      ];
      void-ext:objectClassPartition [
      void:class ?object ;
      void:distinctObjects ?objectCount ;
      ]
    ] .
  }
  FILTER (?sparql_endpoint = ?_sparqlendpoint_iri)
} ORDER BY DESC(?subjectCount)
