#+ endpoint: https://graphdb.dumontierlab.com/repositories/shapes-registry
#+ endpoint_in_url: False
#+ summary: Show statistics for the indexed semantic resources types 
#+ description: Return the count of repositories and shapes files per semantic resources types
#+ tags:
#+   - Statistics overview
#+ method: GET
# pagination: 100

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <https://schema.org/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX shex: <http://www.w3.org/ns/shex#>
PREFIX void: <http://rdfs.org/ns/void#>
SELECT DISTINCT ?shape_type (count(distinct ?repository) AS ?repos_count) (count(distinct ?shape_file) AS ?file_count)
WHERE { 
    ?shape_file a schema:SoftwareSourceCode ;
        a ?shape_type ;
        schema:codeRepository ?repository .
    FILTER(?shape_type != schema:SoftwareSourceCode)
} GROUP BY ?shape_type
